# Generated by Django 5.1.6 on 2025-02-08 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('base_currency', models.CharField(max_length=5)),
                ('quote_currency', models.CharField(max_length=5)),
                ('min_quantity', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_trades', to='exchange.ordermodel')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='exchange.ordermodel')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.tradingpair')),
            ],
        ),
    ]
