# Generated by Django 5.1.6 on 2025-02-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='side',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('FILLED', 'FILLED'), ('CANCELLED', 'CANCELLED'), ('REJECTED', 'REJECTED')], default='NEW', max_length=10),
        ),
    ]
