name: macOS Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    needs: build
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11
        python -m pip install cmake

    # Download build artifacts
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: binary-macos
        path: backend/build/

    # Configure CMake
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    # Run tests
    - name: Test
      working-directory: build
      run: ctest --output-on-failure -V

    # Upload test results
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-macos
        path: build/Testing/
      if: always()