name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11
        python -m pip install cmake
        python -m venv env

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        export PYTHON_PATH=$(which python3)
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DPython_EXECUTABLE=$PYTHON_PATH \
          -DPython_ROOT_DIR=${{github.workspace}}/env \
          -Dpybind11_DIR=$(python3 -c "import pybind11; print(pybind11.get_cmake_dir())")

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary-macos
        path: build/backend/trading_core.so