name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pybind11
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11

    - name: Create build directory
      run: cmake -E make_directory ${{github.workspace}}/backend/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/backend/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/backend/build
      run: cmake --build .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary-macos
        path: ${{github.workspace}}/backend/build/trading_core.so