name: Ubuntu Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11
        python -m pip install cmake
        python -m venv ${{github.workspace}}/env
        source ${{github.workspace}}/env/bin/activate

    - name: Configure CMake 
      run: |
        mkdir -p build
        cd build
        cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DPython_EXECUTABLE=${{github.workspace}}/env/bin/python3.11 \
        -DPython_ROOT_DIR=${{github.workspace}}/env \
        -Dpybind11_DIR=${{github.workspace}}/env/lib/python3.11/site-packages/pybind11/share/cmake/pybind11

    - name: Build
      working-directory: build
      run: cmake --build .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary-ubuntu
        path: backend/build/trading_core.so