name: Ubuntu Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11
        python -m pip install cmake
        python -m venv env
        source env/bin/activate

    - name: Configure CMake 
      run: |
        mkdir -p build
        cd build
        cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DPython_EXECUTABLE=$(which python3) \
        -DPython_ROOT_DIR=$(python3 -c "import sys; print(sys.prefix)") \
        -Dpybind11_DIR=$(python3 -c "import pybind11; print(pybind11.get_cmake_dir())")

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary-ubuntu
        path: build/backend/trading_core.so