name: macOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pybind11
        python -m pip install cmake

    # Debugging: Print Python version and location
    - name: Check Python Version
      run: |
        python --version
        which python

    # Install CxxTest
    - name: Install CxxTest
      run: |
        brew install cxxtest

    # Add CxxTest headers to include path
    - name: Export CxxTest Include Path
      run: |
        export CXXTEST_DIR=$(brew --prefix cxxtest)/share/cxxtest
        echo "CXXTEST_DIR=$CXXTEST_DIR" >> $GITHUB_ENV

    # Configure CMake
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DPython_EXECUTABLE=$(which python3) \
          -DCxxTest_DIR=$(brew --prefix cxxtest)/share/cmake/CxxTest

    # Build the project
    - name: Build
      working-directory: build
      run: cmake --build .

    # Upload the artifact
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary-macos
        path: backend/build/trading_core.so